### ISSUE TITLE
what does this library do? 

### ISSUE THREAD

**Issue by kcochibili** [ashqal/NightOwl#4]
This library looks interesting but the Readme barely describes the function of this project. 
all it says is "It is an experimental project for switching day/night mode on Andorid" can you describe in more details  what you mean by that?

**Comment by ashqal** [comment]
It is a framework to hook view created and read some attribute from xml to change the skin dynamically. Here is the [demo video](https://youtu.be/TV2_zAm446Q) on youtube. Thank you for your attention and I will close this issue.
